import 'package:flutter/material.dart';

class LightThemeColors {
  static ColorScheme colorScheme = const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff96b29c),
    surfaceTint: Color(0xff96b29c),
    onPrimary: Color(0xff07230d),
    primaryContainer: Color(0xffd7e5d9),
    onPrimaryContainer: Color(0xff4a6650),
    secondary: Color(0xffb296ac),
    onSecondary: Color(0xff1f0319),
    secondaryContainer: Color(0xffe3d5df),
    onSecondaryContainer: Color(0xff664a60),
    tertiary: Color(0xffea965a),
    onTertiary: Color(0xff380000),
    tertiaryContainer: Color(0xfff9dfcd),
    onTertiaryContainer: Color(0xff843000),
    error: Color(0xffba1a1a),
    onError: Color(0xffffffff),
    errorContainer: Color(0xffffdad6),
    onErrorContainer: Color(0xff410002),
    surface: Color(0xfff6fafe),
    onSurface: Color(0xff181c1f),
    onSurfaceVariant: Color(0xff41484d),
    outline: Color(0xff717f7e),
    outlineVariant: Color(0xffc1c7ce),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xff2c3135),
    onInverseSurface: Color(0xffeef1f6),
    inversePrimary: Color(0xffcbd9cd),
    primaryFixed: Color(0xffd7e5d9),
    onPrimaryFixed: Color(0xff07230d),
    primaryFixedDim: Color(0xffcbd9cd),
    onPrimaryFixedVariant: Color(0xff17331b),
    secondaryFixed: Color(0xffe3d5df),
    onSecondaryFixed: Color(0xff1f0319),
    secondaryFixedDim: Color(0xffd9cbd5),
    onSecondaryFixedVariant: Color(0xff664a60),
    tertiaryFixed: Color(0xfff9dfcd),
    onTertiaryFixed: Color(0xff380000),
    tertiaryFixedDim: Color(0xfff5cbac),
    onTertiaryFixedVariant: Color(0xff843000),
    surfaceDim: Color(0xffd7dadf),
    surfaceBright: Color(0xffffffff),
    surfaceContainerLowest: Color(0xffffffff),
    surfaceContainerLow: Color(0xfff0f4f8),
    surfaceContainer: Color(0xffebeef3),
    surfaceContainerHigh: Color(0xffe5e8ed),
    surfaceContainerHighest: Color(0xffdfe3e7),
  );

  /// Custom Colors
// static const Color fourthColor = Color(0xFFF2A964);
}
